server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**
        - id: details-service
          uri: lb://details-service
          predicates:
            - Path=/api/details/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/