server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: C:\ARJUN\Java\Student\config-server
          # For production, use a real Git repository

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 8092f3a42fbb905ea5a4e4edba230b28517920d6ba5d6e24570f3acc90f97f3d
  expiration: 36000000  # 10 hours in milliseconds